// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as ClientOptions, TDataShape } from "./client";
import { client as _heyApiClient } from "./client.gen";
import type {
  JobsGetJobsAdvancedData,
  JobsGetJobsAdvancedErrors,
  JobsGetJobsAdvancedResponses,
  JobsGetJobsData,
  JobsGetJobsErrors,
  JobsGetJobsResponses,
  UtilsHealthcheckData,
  UtilsHealthcheckResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export class UtilsService {
  /**
   * Healthcheck
   */
  public static utilsHealthcheck<ThrowOnError extends boolean = false>(
    options?: Options<UtilsHealthcheckData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      UtilsHealthcheckResponses,
      unknown,
      ThrowOnError
    >({
      url: "/api/healthcheck/",
      ...options,
    });
  }
}

export class JobsService {
  /**
   * Get Jobs
   */
  public static getJobs<ThrowOnError extends boolean = false>(
    options?: Options<JobsGetJobsData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      JobsGetJobsResponses,
      JobsGetJobsErrors,
      ThrowOnError
    >({
      url: "/api/jobs",
      ...options,
    });
  }

  /**
   * Get Jobs Advanced
   */
  public static getJobsAdvanced<ThrowOnError extends boolean = false>(
    options?: Options<JobsGetJobsAdvancedData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      JobsGetJobsAdvancedResponses,
      JobsGetJobsAdvancedErrors,
      ThrowOnError
    >({
      url: "/api/jobs/advanced",
      ...options,
    });
  }
}
