// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options,
  createClient,
  createConfig,
} from "@hey-api/client-fetch";
import type {
  JobsGetJobsData,
  JobsGetJobsError,
  JobsGetJobsResponse,
  UtilsHealthCheckData,
  UtilsHealthCheckResponse,
} from "./types.gen";

export const client = createClient(createConfig());

export class UtilsService {
  /**
   * Health Check
   */
  public static utilsHealthCheck<ThrowOnError extends boolean = false>(
    options?: Options<UtilsHealthCheckData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      UtilsHealthCheckResponse,
      unknown,
      ThrowOnError
    >({
      ...options,
      url: "/api/health-check/",
    });
  }
}

export class JobsService {
  /**
   * Get Jobs
   */
  public static getJobs<ThrowOnError extends boolean = false>(
    options?: Options<JobsGetJobsData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      JobsGetJobsResponse,
      JobsGetJobsError,
      ThrowOnError
    >({
      ...options,
      url: "/api/jobs",
    });
  }
}
