// This file is auto-generated by @hey-api/openapi-ts

export type HttpValidationError = {
  detail?: Array<ValidationError>;
};

export type JobRead = {
  link: string;
  title: string;
  location: string;
  company: string;
  description?: string | null;
  employment_type?: string | null;
  seniority_level?: string | null;
  job_function?: string | null;
  industries?: string | null;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type UtilsHealthCheckData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/health-check/";
};

export type UtilsHealthCheckResponses = {
  /**
   * Successful Response
   */
  200: boolean;
};

export type UtilsHealthCheckResponse =
  UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses];

export type JobsGetJobsData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    search?: string;
  };
  url: "/api/jobs";
};

export type JobsGetJobsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type JobsGetJobsError = JobsGetJobsErrors[keyof JobsGetJobsErrors];

export type JobsGetJobsResponses = {
  /**
   * Successful Response
   */
  200: Array<JobRead>;
};

export type JobsGetJobsResponse =
  JobsGetJobsResponses[keyof JobsGetJobsResponses];
