/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as LayoutIndexImport } from "./routes/_layout/index";
import { Route as AdvancedImport } from "./routes/advanced";
import { Route as JobsImport } from "./routes/jobs";

// Create/Update Routes

const JobsRoute = JobsImport.update({
  id: "/jobs",
  path: "/jobs",
  getParentRoute: () => rootRoute,
} as any);

const AdvancedRoute = AdvancedImport.update({
  id: "/advanced",
  path: "/advanced",
  getParentRoute: () => rootRoute,
} as any);

const LayoutIndexRoute = LayoutIndexImport.update({
  id: "/_layout/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/jobs": {
      id: "/jobs";
      path: "/jobs";
      fullPath: "/jobs";
      preLoaderRoute: typeof JobsImport;
      parentRoute: typeof rootRoute;
    };
    "/advanced": {
      id: "/advanced";
      path: "/advanced";
      fullPath: "/advanced";
      preLoaderRoute: typeof AdvancedImport;
      parentRoute: typeof rootRoute;
    };
    "/_layout/": {
      id: "/_layout/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof LayoutIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/jobs": typeof JobsRoute;
  "/advanced": typeof AdvancedRoute;
  "/": typeof LayoutIndexRoute;
}

export interface FileRoutesByTo {
  "/jobs": typeof JobsRoute;
  "/advanced": typeof AdvancedRoute;
  "/": typeof LayoutIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/jobs": typeof JobsRoute;
  "/advanced": typeof AdvancedRoute;
  "/_layout/": typeof LayoutIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/jobs" | "/advanced" | "/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/jobs" | "/advanced" | "/";
  id: "__root__" | "/jobs" | "/advanced" | "/_layout/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  JobsRoute: typeof JobsRoute;
  AdvancedRoute: typeof AdvancedRoute;
  LayoutIndexRoute: typeof LayoutIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  JobsRoute: JobsRoute,
  AdvancedRoute: AdvancedRoute,
  LayoutIndexRoute: LayoutIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/jobs",
        "/advanced",
        "/_layout/"
      ]
    },
    "/jobs": {
      "filePath": "jobs.tsx"
    },
    "/advanced": {
      "filePath": "advanced.tsx"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
